#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.

if [ $# -ne 1 ]; then
    exit 1
fi
ip_address=$1
ping -c 5 $ip_address
if [ $? -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    echo "Ping to $ip_address failed."
fi

